apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-08T15:38:52Z"
  labels:
    run: busybox
  name: busybox
  namespace: s-30
  resourceVersion: "4034195"
  uid: 70217d99-fc6e-466a-b39b-b4413ad720c8
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c8vjr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-c8vjr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:38:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:38:52Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:38:52Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:38:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://60deb7604ba4947e53987100b6d8402f8351a10442b3d4b9454562b4bf677a90
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8
    lastState:
      terminated:
        containerID: containerd://60deb7604ba4947e53987100b6d8402f8351a10442b3d4b9454562b4bf677a90
        exitCode: 0
        finishedAt: "2024-01-08T15:39:38Z"
        reason: Completed
        startedAt: "2024-01-08T15:39:38Z"
    name: busybox
    ready: false
    restartCount: 3
    started: false
    state:
      waiting:
        message: back-off 40s restarting failed container=busybox pod=busybox_s-30(70217d99-fc6e-466a-b39b-b4413ad720c8)
        reason: CrashLoopBackOff
  hostIP: 95.217.135.101
  phase: Running
  podIP: 10.233.65.212
  podIPs:
  - ip: 10.233.65.212
  qosClass: BestEffort
  startTime: "2024-01-08T15:38:52Z"
