apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-08T15:22:45Z"
  labels:
    run: nginx1
    project: practice
    author: BEKHZOD
  name: nginx1
  namespace: s-30
  resourceVersion: "4030678"
  uid: 48fae773-62d6-4fb2-a974-1de8dce3a01a
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c4msm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-c4msm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:22:45Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:22:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:22:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T15:22:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://044b7d1be34771f0d6149349c5507e4c81ea3da8df6d7c0b7406e167d5aa895a
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:2bdc49f2f8ae8d8dc50ed00f2ee56d00385c6f8bc8a8b320d0a294d9e3b49026
    lastState: {}
    name: nginx1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-08T15:22:46Z"
  hostIP: 95.217.7.185
  phase: Running
  podIP: 10.233.66.181
  podIPs:
  - ip: 10.233.66.181
  qosClass: BestEffort
  startTime: "2024-01-08T15:22:45Z"
